<?php
$modversion['name'] = _MI_TAGMEMO_NAME;
$modversion['description'] = _MI_TAGMEMO_DESC;
$modversion['version'] = 0.2;
$modversion['credits'] = '';
$modversion['author'] = 'yosha_01, twodash, nao-pon, fugafuga, comodita, argon (Alphabetical descending)';
$modversion['help'] = 'help.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/tagmemo_slogo.png';
$modversion['dirname'] = 'tagmemo';
 
// Admin
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";
 
// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][] = array(	'name' => _MI_TAGMEMO_LIST,
								'url'  => 'index.php' );
$modversion['sub'][] = array(	'name' => _MI_TAGMEMO_EDIT,
								'url'  => 'edit.php' );
$modversion['sub'][] = array(	'name' => _MI_TAGMEMO_CLOUD,
								'url'  => 'tagcloud.php' );

// Templates
/* $modversion['templates'][0]['file'] = 'index.html';
$modversion['templates'][0]['description'] = 'tagmemo'; */
$modversion['templates'][0]['file'] = 'tagmemo_detail.html';
$modversion['templates'][0]['description'] = 'detail content of memo';
$modversion['templates'][1]['file'] = 'tagmemo_edit.html';
$modversion['templates'][1]['description'] = 'tagmemo';
$modversion['templates'][2]['file'] = 'tagmemo_tagcloud.html';
$modversion['templates'][2]['description'] = 'list of tag';
$modversion['templates'][3]['file'] = 'tagmemo_list.html';
$modversion['templates'][3]['description'] = 'tagmemo_list';
$modversion['templates'][4]['file'] = 'tagmemo_list_ajax.html';
$modversion['templates'][4]['description'] = 'tagmemo_list_ajax';
$modversion['templates'][5]['file'] = 'tagmemo_quickedit.html';
$modversion['templates'][5]['description'] = 'tagmemo_quickedit.html';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "tagmemo";
$modversion['tables'][1] = "tagmemo_tag";
$modversion['tables'][3] = "tagmemo_rel";

//blocks
$modversion['blocks'][1]['file'] = "tag_block.php";
$modversion['blocks'][1]['name'] = _MI_TAGMEMO_POPULAR_TAG_BLOCK;
$modversion['blocks'][1]['show_func'] = "b_tagmemo_poulartag";
$modversion['blocks'][1]['template'] = "popular_tag.html";
$modversion['blocks'][1]['description'] = "Popular Tags";

$modversion['blocks'][2]['file'] = "tag_block.php";
$modversion['blocks'][2]['name'] = _MI_TAGMEMO_RECENT_TAG_BLOCK;
$modversion['blocks'][2]['show_func'] = "b_tagmemo_recenttag"; 
$modversion['blocks'][2]['template'] = "recent_tag.html";
$modversion['blocks'][2]['description'] = "Recent Tags";

$modversion['blocks'][3]['file'] = "tag_block.php";
$modversion['blocks'][3]['name'] = _MI_TAGMEMO_SERCH_TAG_BLOCK;
$modversion['blocks'][3]['show_func'] = "b_tagmemo_relatedtag"; 
$modversion['blocks'][3]['template'] = "related_tag.html";
$modversion['blocks'][3]['description'] = "Related Tags";

$modversion['blocks'][4]['file'] = "tag_block.php";
$modversion['blocks'][4]['name'] = "Memo ID Search";
$modversion['blocks'][4]['show_func'] = "b_tagmemo_id_serch"; 
$modversion['blocks'][4]['template'] = "id_search.html";
$modversion['blocks'][4]['description'] = "Memo ID Search";

$modversion['blocks'][5]['file'] = "tag_block.php";
$modversion['blocks'][5]['name'] = _MI_TAGMEMO_TAGCLOUD_BLOCK;
$modversion['blocks'][5]['show_func'] = "b_tagmemo_cloud"; 
$modversion['blocks'][5]['template'] = "cloud_block.html";
$modversion['blocks'][5]['description'] = "Tagmemo Tag Cloud";

$modversion['hasConfig'] = 1;
$modversion['config'][] = array(
	'name' => 'ff_plugin',
	'title' => '_MI_TAGMEMO_USE_FF_PLUGIN',
	'description' => '',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => '0',
	);
$modversion['config'][] = array(
	'name' => 'per_page',
	'title' => '_MI_TAGMEMO_PER_PAGE',
	'description' => '',
	'formtype' => 'textbox',
	'valuetype' => 'int',
	'default' => '10',
	);
$modversion['config'][] = array(
	'name' => 'use_autolink',
	'title' => '_MI_TAGMEMO_USE_AUTOLINK',
	'description' => '',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => '0',
	);
$modversion['config'][] = array(
	'name' => 'kakasi_path',
	'title' => '_MI_TAGMEMO_KAKASI_PATH',
	'description' => '',
	'formtype' => 'textbox',
	'valuetype' => 'string',
	'default' => '/usr/bin/kakasi',
	);
$modversion['config'][] = array(
	'name' => 'tagpopup_list',
	'title' => '_MI_TAGMEMO_TAGPOPUP_LIST',
	'description' => '',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => '0',
	);
$modversion['config'][] = array(
	'name' => 'tagpopup_detail',
	'title' => '_MI_TAGMEMO_TAGPOPUP_DETAIL',
	'description' => '',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => '0',
	);
$modversion['config'][] = array(
	'name' => 'tagpopup_cloud',
	'title' => '_MI_TAGMEMO_TAGPOPUP_CLOUD',
	'description' => '',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => '0',
	);
$modversion['config'][] = array(
	'name' => 'tagmemo_shorturl',
	'title' => '_MI_TAGMEMO_SHORTURL',
	'description' => '',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => '0',
	);

// hold setting value when module update.
if( ! empty( $_POST['fct'] ) && ! empty( $_POST['op'] ) && $_POST['fct'] == 'modulesadmin' && $_POST['op'] == 'update_ok' && $_POST['dirname'] == $modversion['dirname'] ) {
	include dirname( __FILE__ ) . "/include/onupdate.inc.php" ;
}
?>